# Site settings
title: TextBundle.org
email:
description: "A community site for the development of the TextBundle standard"
baseurl:
url: "http://textbundle.org"
twitter_username:  textbundle
github_username:  textbundle

# Build settings
markdown: kramdown
permalink: pretty